mail.host=smtp.gmail.com
mail.port=587
mail.username=hansaprabhathjayasundhara@gmail.com
mail.password=gcma srxs wtvz dhfe
app.mail=hansaprabhathjayasundhara@gmail.com
app.name=ShoppingStore
app.url=http://localhost:8080/clothmaster